$(document).ready(function(){
	$("#spidercookiesentire").hide();
	$("#pumpkinrollsentire").hide();
	$("#mummypiesentire").hide();

	$(".brief_info").hide();

	$(".first_recipe").click(function(){
		$(".first_recipe").addClass("active");
		$(".second_recipe").removeClass("active");
		$(".third_recipe").removeClass("active");
		$(".first_brief").slideDown(500);
		$(".second_brief").hide();
		$(".third_brief").hide();
		$("#pumpkinrollsentire").hide();
		$("#mummypiesentire").hide();
		$("#spidercookiesentire").fadeIn(1150);
	});
	$(".second_recipe").click(function(){
		$(".first_recipe").removeClass("active");
		$(".second_recipe").addClass("active");
		$(".third_recipe").removeClass("active");
		$(".second_brief").slideDown(500);
		$(".first_brief").hide();
		$(".third_brief").hide();
		$("#spidercookiesentire").hide();
		$("#mummypiesentire").hide();
		$("#pumpkinrollsentire").fadeIn(1150);
	});
	$(".third_recipe").click(function(){
		$(".first_recipe").removeClass("active");
		$(".second_recipe").removeClass("active");
		$(".third_recipe").addClass("active");
		$(".third_brief").slideDown(500);
		$(".second_brief").hide();
		$(".first_brief").hide();
		$("#pumpkinrollsentire").hide();
		$("#spidercookiesentire").hide();
		$("#mummypiesentire").fadeIn(1150);
	});
});